name: Özellik isteği
description: Yeni bir özellik öner
labels: [enhancement]
body:
  - type: textarea
    id: motivation
    attributes: {label: Motivasyon, description: Neden gerekli?}
    validations: {required: true}
